var searchData=
[
  ['oextalkcoverarr_0',['oeXtalkCoverArr',['../group__argus__xtk__cli.html#ga4a4c215670e069650f5c403cd632c724',1,'argus_xtalk_cal_cli.c']]],
  ['oextalknocoverarr_1',['oeXtalkNoCoverArr',['../group__argus__xtk__cli.html#gac71d8dd4d399ef6d8b0fb23d92201d50',1,'argus_xtalk_cal_cli.c']]],
  ['of_20advanced_20measurement_20modes_2',['Removal of Dual-Measurement Modes And Adding of Advanced Measurement Modes',['../migration_guide.html#autotoc_md68',1,'']]],
  ['of_20changes_3',['of Changes',['../migration_guide.html#autotoc_md65',1,'Overview of Changes'],['../migration_guide.html#autotoc_md67',1,'Overview of Changes']]],
  ['of_20data_20function_20changes_20extensions_20new_20items_4',['Overview of Data &amp; Function Changes / Extensions / new Items',['../migration_guide.html#autotoc_md62',1,'']]],
  ['of_20distinct_20global_20range_20offsets_20for_20low_20and_20high_20power_20stages_5',['Introduction of distinct global range offsets for low and high power stages',['../migration_guide.html#autotoc_md66',1,'']]],
  ['of_20dual_20measurement_20modes_20and_20adding_20of_20advanced_20measurement_20modes_6',['Removal of Dual-Measurement Modes And Adding of Advanced Measurement Modes',['../migration_guide.html#autotoc_md68',1,'']]],
  ['offset_7',['Global Range Offset',['../explorer_app_cmd_details.html#cmd_cal_range_offset',1,'']]],
  ['offset_20table_8',['Pixel Range Offsets - Reset Offset Table',['../explorer_app_cmd_details.html#cmd_cal_offsets_rst',1,'']]],
  ['offset_20tables_9',['Changed Data Types for Crosstalk and Offset Tables',['../migration_guide.html#autotoc_md71',1,'']]],
  ['offsets_10',['Pixel Range Offsets',['../explorer_app_cmd_details.html#cmd_cal_offsets',1,'']]],
  ['offsets_20calibration_20sequence_20sample_20time_11',['Range Offsets Calibration Sequence - Sample Time',['../explorer_app_cmd_details.html#cmd_cal_offsets_smpl_time',1,'']]],
  ['offsets_20for_20low_20and_20high_20power_20stages_12',['Introduction of distinct global range offsets for low and high power stages',['../migration_guide.html#autotoc_md66',1,'']]],
  ['offsets_20reset_20offset_20table_13',['Pixel Range Offsets - Reset Offset Table',['../explorer_app_cmd_details.html#cmd_cal_offsets_rst',1,'']]],
  ['on_20eeprom_20readout_20sequence_14',['2. Further Tests on EEPROM Readout Sequence',['../faq.html#autotoc_md79',1,'']]],
  ['on_20using_20the_20sci_20interface_15',['Python Example on Using the SCI Interface',['../explorer_app.html#explorer_app_python_example',1,'']]],
  ['onerror_16',['OnError',['../explorer__tasks_8c.html#ae3ec3979a753cbf6f205246cb5e7b40f',1,'explorer_tasks.c']]],
  ['opensda_20debugger_17',['Debug the Project with the OpenSDA Debugger',['../mcuxpresso.html#autotoc_md12',1,'']]],
  ['opensda_20drivers_18',['Download and install the OpenSDA drivers',['../mcuxpresso.html#autotoc_md11',1,'']]],
  ['operation_20principle_19',['Operation Principle',['../sw_api.html#sw_api_principle',1,'']]],
  ['operations_20',['Explorer Macro Operations',['../group__explorer__macro.html',1,'']]],
  ['opt_5felec_5fxtk_5fampl_5flmt_21',['OPT_ELEC_XTK_AMPL_LMT',['../group__argus__xtk__cli.html#gaf69a2f918c6f4c7a8776d59d32076caa',1,'argus_xtalk_cal_cli.h']]],
  ['optical_22',['Optical',['../structargus__cal__p2pxtalk__t.html#adef1bc3682c932cdb3cae10173f6a6ce',1,'argus_cal_p2pxtalk_t']]],
  ['or_20accuracy_23',['Decreased Device Performance or Accuracy',['../faq.html#autotoc_md77',1,'']]],
  ['or_20yields_20timeout_20error_206_24',['The Measurement Never Finishes or Yields Timeout Error (-6)',['../faq.html#autotoc_md80',1,'']]],
  ['ore_20address_200_25',['Single Device Version (Basic Mode ore Address == 0)',['../explorer_app_cmd_details.html#autotoc_md43',1,'']]],
  ['output_20mode_26',['Data Output Mode',['../explorer_app_cmd_details.html#cmd_cfg_output_mode',1,'']]],
  ['output_20mode_20enumerator_27',['Measurement Data Output Mode Enumerator',['../explorer_app_cmd_details.html#autotoc_md46',1,'']]],
  ['outputpower_28',['OutputPower',['../structargus__meas__frame__t.html#a4aad62a4d40928a3907b8ae569a740b2',1,'argus_meas_frame_t']]],
  ['overview_29',['Overview',['../index.html#autotoc_md0',1,'API Overview'],['../sw_api.html',1,'Architectural Overview'],['../explorer_app_cmd_overview.html',1,'Command Overview'],['../sw_api.html#sw_api_overview',1,'Overview'],['../explorer_app.html#autotoc_md41',1,'Overview'],['../reference_board.html#reference_board_overview',1,'Overview'],['../porting_guide.html#autotoc_md26',1,'S2PI Overview']]],
  ['overview_20of_20changes_30',['Overview of Changes',['../migration_guide.html#autotoc_md65',1,'Overview of Changes'],['../migration_guide.html#autotoc_md67',1,'Overview of Changes']]],
  ['overview_20of_20data_20function_20changes_20extensions_20new_20items_31',['Overview of Data &amp; Function Changes / Extensions / new Items',['../migration_guide.html#autotoc_md62',1,'']]]
];
